apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  POSTGRES_USER: c2E=  # base64 encoded value of 'sa'
  POSTGRES_PASSWORD: YWRtaW4=  # base64 encoded value of 'admin'
  MONGO_INITDB_ROOT_USERNAME: c2E=  # base64 encoded value of 'sa'
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=  # base64 encoded value of 'admin'
  EUREKA_USERNAME: YWRtaW4=  # base64 encoded value of 'admin'
  EUREKA_PASSWORD: YWRtaW4=  # base64 encoded value of 'admin'
  REDIS_PASSWORD: ZVlWWDdFd1ZtbXhLUENEbXdNdHlLVmdlOG9MZDI4dDgx  # base64 encoded value of 'eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81'
  SECRET: a2x0bjEyMzQ1Ng==  # base64 encoded value of 'kltn123456'
  MINIO_ROOT_USER: YWRtaW4=  # base64 encoded value of 'admin'
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==  # base64 encoded value of 'minioadmin'
#  PROMETHEUS_USERNAME: YWRtaW4= # base64 encoded value of 'admin'
#  PROMETHEUS_PASSWORD: YWRtaW4= # base64 encoded value of 'admin'
