apiVersion: v1
kind: Service
metadata:
  name: message-broker
spec:
  selector:
    app: message-broker
  ports:
    - name: message-broker
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: message-broker-host
      protocol: TCP
      port: 29092
      targetPort: 29092