apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  type: NodePort
  ports:
    - port: 9187
      targetPort: 9187
      nodePort: 30187
  selector:
    app: postgres-exporter