apiVersion: v1
kind: Service
metadata:
  name: individual-service
spec:
  selector:
    app: individual-service
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: LoadBalancer