global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'config-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['config-service:8888']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'file-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['file-service:9001']

  - job_name: 'individual-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['individual-service:9002']

  - job_name: 'postgres-exporter'
    scrape_interval: 15s
    static_configs:
        - targets: [ "postgres-exporter:9187" ]

  - job_name: 'mongo-exporter'
    scrape_interval: 15s
    static_configs:
        - targets: [ "mongo-exporter:9216" ]