apiVersion: v1
kind: Service
metadata:
  name: postgres-notification-exporter
  labels:
    app: postgres-notification-exporter
spec:
  type: NodePort
  ports:
    - port: 9187
      targetPort: 9187
      nodePort: 30188
  selector:
    app: postgres-notification-exporter